---
driver:
  name: vagrant
  network:
  - ["forwarded_port", { guest: 9700, host: 9700}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[pritunl::default]
    attributes:
